name: Deploy

on:
  push:
    branches: [ "master" ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_HOST: ${{ secrets.SSH_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr
        path: ./*
        remote_path: /home/ubuntu/app/backend
        remote_host: ${{ env.SSH_HOST }}
        remote_user: ${{ env.SSH_USERNAME }}
        remote_key: ${{ env.SSH_PRIVATE_KEY }}
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/app/backend
          nvm use default
          yarn -v
          yarn install
          yarn build:ts
          pm2 restart app-backend